name: sytle_check

on:
  pull_request:
  push:
    branches:
      - develop
      - master
jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set-up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.6.1

      - name: Test style
        run: python -m ruff check ./src
